# Generated by Django 4.0.3 on 2022-04-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_joboffer_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='currency',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
    ]
