# Generated by Django 4.0.3 on 2022-04-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_branch_alter_joboffer_currency_joboffer_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='branch',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
    ]
