# Generated by Django 4.0.3 on 2022-04-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.city'),
        ),
    ]
