# Generated by Django 4.0.3 on 2022-04-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_joboffer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='city',
        ),
    ]
