# Generated by Django 4.0.3 on 2022-04-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_location_joboffer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='branch',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='city',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.city'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_nature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='max_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
