# Generated by Django 4.0.3 on 2022-04-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_joboffer_address_alter_joboffer_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='job_nature',
            new_name='working_mode',
        ),
    ]
